# action.yml
name: 'Terrafrom Docs Build'
description: 'Build docs site by generating data & publishing npm build to docs branch.'
inputs:
  tf-config-path:  # id of input
    description: 'Terraform Configuration Path'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tf-config-path }}
