# action.yml
name: 'Terraform Docs Build'
description: 'Build docs site by generating data & publishing npm build to docs branch.'
inputs:
  tf-module-path:  # id of input
    description: 'Terraform Configuration Path'
    required: false
    default: '.'
  data-output-path:  # id of input
    description: 'Terraform Configuration Path'
    required: false
    default: './docs'
  tf-module-recruse:
    description: 'Should the given tf-module-path be recursed for sub-modules.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tf-module-path }}
    - ${{ inputs.data-output-path }}
    - ${{ inputs.tf-module-recruse }}
