#build stage
FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN go get -d -v ./...
RUN go build -o /go/bin/app -v ./...

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
RUN /app 


ENTRYPOINT /app
LABEL Name=tfconfigdocs Version=0.0.1

#final stage
FROM node:18.3.0-alpine
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
ENTRYPOINT /app
LABEL Name=tfconfigdocs Version=0.0.1
EXPOSE 3000
